### ISSUE TITLE
Meta/Version/JunoFile deletion

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#220] opened 2024-04-07 12:39 UTC
1. Recursive deletion needed so users don't create orphan data. If we delete a Shot it should delete all it's children, and its childrens children to avoid this.
2.  Need ability to delete juno files.

**Comment by aldmbmtl** [comment] 2024-05-21 01:35
This is a duplicate of https://github.com/juno-fx/luna/issues/106

**Closed by aldmbmtl** 2024-05-21 01:35 UTC
